version: 2.1

orbs:
  node: cloudify/public-unittest-orb@1.0.0 #orb version

checkout:
  post:
    - >
      if [ -n "$CI_PULL_REQUEST" ]; then
        PR_ID=${CI_PULL_REQUEST##*/}
        git fetch origin +refs/pull/$PR_ID/merge:
        git checkout -qf FETCH_HEAD
      fi

executors:

  py36:
    docker:
      - image: circleci/python:3.6

  wagon_generator:
    machine:
      image: ubuntu-1604:201903-01

  arm_wagon_generator:
    machine:
      image: ubuntu-2004:202101-01
      resource_class: arm.medium

  cloudify-machine-py3:
    machine:
      image: ubuntu-1604:201903-01

commands:

  generate_py36_wagon:
    steps:
      - run:
          name: Create Workspace Build directory.
          command: mkdir -p workspace/build
      - run:
          name: Build py36 Wagon
          command: |
              git clone https://github.com/cloudify-cosmo/cloudify-wagon-build-containers.git
              docker build -t cloudify-wagon-builder-centos cloudify-wagon-build-containers/centos_7_py3
              docker run -v ~/project/:/packaging cloudify-wagon-builder-centos
      - run:
          name: copy wagon to workspace
          command: cp *.wgn workspace/build/
      - persist_to_workspace:
          root: workspace
          paths:
            - build/*

  generate_arch64_wagon:
    steps:
      - run:
          name: Create Workspace Build directory.
          command: mkdir -p workspace/build
      - run:
          name: Build py36 Wagon
          command: |
              git clone https://github.com/cloudify-cosmo/cloudify-wagon-build-containers.git
              docker build -t centos_aarch64 cloudify-wagon-build-containers/aarch_64/centos_7_py3
              docker run -v ~/project/:/packaging centos_aarch64
      - run:
          name: copy wagon to workspace
          command: cp *.wgn workspace/build/
      - persist_to_workspace:
          root: workspace
          paths:
            - build/*

  generate_rhel_py36_wagon:
    steps:
      - run:
          name: Create Workspace Build directory.
          command: mkdir -p workspace/build
      - run:
          name: Build RHEL py36 Wagon
          command: |
              git clone https://github.com/cloudify-cosmo/cloudify-wagon-build-containers.git
              docker build -t cloudify-wagon-builder-redhat cloudify-wagon-build-containers/redhat_7_py3 --build-arg USERNAME="$USERNAME" --build-arg PASSWORD="$PASSWORD"
              docker run -v ~/project/:/packaging cloudify-wagon-builder-redhat
      - run:
          name: copy wagon to workspace
          command: cp *.wgn workspace/build/
      - persist_to_workspace:
          root: workspace
          paths:
            - build/*



  build_archive:
    steps:
      - attach_workspace:
          at: workspace
      - run:
          name: Create Workspace Build directory.
          command: mkdir -p workspace/build
      - run:
          name: Build Bundle
          command: |
            git clone https://github.com/cloudify-incubator/cloudify-ecosystem-test.git
            pip install -e cloudify-ecosystem-test
            python -c 'from ecosystem_cicd_tools import packaging; packaging.build_plugins_bundle_with_workspace()'
      - persist_to_workspace:
          root: workspace
          paths:
            - build/*


  create_manager_container_py3:
    steps:
      - run:
          name: "Pull Submodules"
          command: |
            git submodule update --init --recursive --remote
      - attach_workspace:
          at: workspace
      - run:
          name: update pip
          command: pip install -U pip===20.3.3
      - run:
          name: install cloudify
          command: |
            pip install -r test-requirements.txt
      - run:
          name: download manager docker image
          command:  wget http://repository.cloudifysource.org/cloudify/6.2.0/ga-release/cloudify-manager-aio-docker-6.2.0-ga.tar
      - run:
          name: load docker manager image
          command: docker load -i cloudify-manager-aio-docker-6.2.0-ga.tar
      - run:
          name: show images
          command: docker images
      - run:
          name: start docker container
          command: docker run --name cfy_manager -d --restart unless-stopped -v /sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /run/lock --security-opt seccomp:unconfined --cap-add SYS_ADMIN --network host cloudify-manager-aio-x86_64
      - run:
          name: wait for starter
          command: docker exec -it cfy_manager cfy_manager wait-for-starter
      - run:
          name: install local project
          command:  pip install https://github.com/cloudify-incubator/cloudify-ecosystem-test/archive/latest.zip

  prepare_test_manager:
    steps:
      - run: ecosystem-test prepare-test-manager -l $TEST_LICENSE -es gcp_credentials=$gcp_credentials --bundle-path workspace/build/cloudify-plugins-bundle.tgz

  run_gke_test:
    steps:
      - run: ecosystem-test local-blueprint-test  -b examples/blueprint-examples/kubernetes/gcp-gke/blueprint.yaml --test-id=gcp-gke  -i resource_prefix=kube-$CIRCLE_BUILD_NUM --on-failure=uninstall-force --timeout=3000

  release_plugin:
    steps:
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote --recursive
      - run:
          name: Download pip
          command: curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
      - run:
          name: Install pip
          command: sudo python get-pip.py
      - run:
          name: Install virtualenv
          command: pip install --user virtualenv
      - run:
          name: Init virtualenv
          command: virtualenv env
      - run:
          name: install tox
          command: pip install --user pygithub
      - run:
          name: upgrade setuptools
          command: pip install --upgrade setuptools
      - run:
          name: install local project
          command: pip install https://github.com/cloudify-incubator/cloudify-ecosystem-test/archive/latest.zip
      - attach_workspace:
          at: workspace
      - run: ecosystem-tests package-release --name cloudify-kubernetes-plugin


  merge_docs:
    steps:
      - attach_workspace:
          at: workspace
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote --recursive
      - run:
          name: Download pip
          command: curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
      - run:
          name: Install pip
          command: sudo python get-pip.py
      - run:
          name: Install virtualenv
          command: pip install --user virtualenv
      - run:
          name: Init virtualenv
          command: virtualenv env
      - run:
          name: install tox
          command: pip install --user pygithub
      - run:
          name: upgrade setuptools
          command: pip install --upgrade setuptools
      - run:
          name: install local project
          command: pip install https://github.com/cloudify-incubator/cloudify-ecosystem-test/archive/latest.zip
      - attach_workspace:
          at: workspace
      - run: ecosystem-tests merge-docs

jobs:

  wagon:
    executor: wagon_generator
    steps:
      - checkout
      - generate_py36_wagon

  arch64_wagon:
    executor: arm_wagon_generator
    steps:
      - checkout
      - generate_arch64_wagon

  rhel_wagon:
    executor: wagon_generator
    steps:
      - checkout
      - generate_rhel_py36_wagon

  build_bundle:
    executor: py36
    steps:
      - checkout
      - build_archive

  kubernetes_integration_tests_py3:
    executor: cloudify-machine-py3
    environment:
      CLOUDIFY_SSL_TRUST_ALL: true
    steps:
      - checkout
      - create_manager_container_py3
      - prepare_test_manager
      - run_gke_test

  release:
    executor: py36
    steps:
      - checkout
      - release_plugin


  merge_docs:
    executor: py36
    steps:
      - checkout
      - merge_docs

workflows:
  version: 2
  tests:
    jobs:
      - node/check_py3_compat_job
      - node/unittests_job
      - node/validate_version_job
      - node/validate_documentation_job
      - wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master)/
      - arch64_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - rhel_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master)/
      - build_bundle:
          filters:
            branches:
              only: /master/
          requires:
            - wagon
            - arch64_wagon
            - rhel_wagon
      - kubernetes_integration_tests_py3:
          requires:
            - build_bundle
          filters:
            branches:
              only: /([0-9\.]*\-build|master)/
      - release:
          filters:
            branches:
              only: /master/
          requires:
            - node/unittests_job
            - wagon
            - rhel_wagon
            - kubernetes_integration_tests_py3
      - merge_docs:
          filters:
            branches:
              only: /master/
          requires:
            - release
            - node/validate_documentation_job

  nightly:
    triggers:
    - schedule:
        cron: "0 1 * * 0,1,3,5"
        filters:
          branches:
            only:
              - master
    jobs:
      - node/check_py3_compat_job
      - node/unittests_job
      - node/validate_version_job
      - wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master)/
      - rhel_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master)/
      - build_bundle:
          filters:
            branches:
              only: /master/
          requires:
            - wagon
            - rhel_wagon
      - kubernetes_integration_tests_py3:
          requires:
            - build_bundle
          filters:
            branches:
              only: /([0-9\.]*\-build|master)/