#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: wordpress
#  labels:
#    app: wordpress
#spec:
#  strategy:
#    type: Recreate
#  template:
#    metadata:
#      labels:
#        app: wordpress
#        tier: frontend
#    spec:
#      containers:
#      - image: wordpress:4.8.0-apache
#        name: wordpress
#        env:
#        - name: WORDPRESS_DB_HOST
#          value: wordpress-mysql
#        - name: WORDPRESS_DB_PASSWORD
#          value: {{ WORDPRESS_PASSWORD }}
#        ports:
#        - containerPort: 80
#          name: wordpress
#        volumeMounts:
#        - name: wordpress-persistent-storage
#          mountPath: /var/www/html
#      volumes:
#      - name: wordpress-persistent-storage
#        persistentVolumeClaim:
#          claimName: wp-pv-claim
#options:
#grace_period_seconds: 5
#propagation_policy: 'Foreground'
#namespace: 'default'
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: wordpress
#  labels:
#    app: wordpress
#spec:
#  ports:
#    - port: 80
#      nodePort: 30080
#  selector:
#    app: wordpress
#    tier: frontend
#  type: LoadBalancer
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: wp-pv-claim
#  labels:
#    app: wordpress
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          # $ kubectl create secret generic mysql-pass --from-file=password.txt
          # make sure password.txt does not have a trailing newline
        - name: MYSQL_ROOT_PASSWORD
          value: {{ MYSQL_ROOT_PASSWORD }}
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-2
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/pv-2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-1
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/pv-1
