tosca_definitions_version: cloudify_dsl_1_3

imports:
  - http://www.getcloudify.org/spec/cloudify/5.0.5/types.yaml
  - plugin:cloudify-kubernetes-plugin

inputs:

  kubernetes_master:
    type: string

node_templates:

  deployment:
    type: cloudify.nodes.kubernetes.resources.BlueprintDefinedResource
    properties:
      client_config:
        configuration:
          api_options:
            host: { get_input: kubernetes_master }
            api_key: { get_secret: kubernetes_token }
            debug: false
            verify_ssl: false
      definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: nginx-deployment
          labels:
            app: nginx
        spec:
          replicas: 3
          selector:
            matchLabels:
              app: nginx
          template:
            metadata:
              labels:
                app: nginx
                name: nely
            spec:
              containers:
              - name: nginx
                image: nginx:1.7.9
                ports:
                - containerPort: 80
