apiVersion: v1
kind: Service
metadata:
  name: test15
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
      nodePort: 20085
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
